### ISSUE TITLE
树莓派4上有安装成功的吗？

### ISSUE THREAD

**Issue by ns-issac** [iFLYOS-OPEN/SDK-EVS-Linux#1]
可以直接在树莓派4上安装吗？需要改什么配置吗？

**Comment by jan4984** [comment]
`SDK-EVS-Linux` should work on any modern Linux distribution with audio input/output supports.
Currently this repository does not focus on how configure variable Linux distributions and hardwares. But any experience about running SDK-EVS-Linux is welcomed.
